### ISSUE TITLE
Enforcer does not work for dict/list

### ISSUE THREAD

**Issue by cmantas** [connor-makowski/type_enforced#17]
```python
@type_enforced.Enforcer
def foo(arg: List):
    pass

@type_enforced.Enforcer
def bar(arg: Dict):
    pass

foo([])
#bar({})
```
these result in 
```
TypeError: (foo): Type mismatch for typed variable `arg`. Expected one of the following `[typing.List]` but got `<class 'list'>` instead.
```
and
```
TypeError: (bar): Type mismatch for typed variable `arg`. Expected one of the following `[typing.Dict]` but got `<class 'dict'>` instead.
```
That's not intended, right?

**Comment by connor-makowski** [comment]
Thank you for the comment. With this module, you do not need to import from typing. For example, you can simply specify `list`. 

EG:

```
>>> import type_enforced
>>> @type_enforced.Enforcer
... def foo(arg: list):
...     pass
... 
>>> @type_enforced.Enforcer
... def bar(arg: dict):
...     pass
... 
>>> foo([])
>>> bar({})
>>> foo({})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/conmak/development/personal/type_enforced/type_enforced/enforcer.py", line 95, in __call__
    self.__check_type__(assigned_vars.get(key), value, key)
  File "/home/conmak/development/personal/type_enforced/type_enforced/enforcer.py", line 117, in __check_type__
    self.__exception__(
  File "/home/conmak/development/personal/type_enforced/type_enforced/enforcer.py", line 34, in __exception__
    raise TypeError(f"({self.__fn__.__qualname__}): {message}")
TypeError: (foo): Type mismatch for typed variable `arg`. Expected one of the following `[<class 'list'>]` but got `<class 'dict'>` instead.
```
 The only time you need to import from typing is when you want to validate an uninitialized class instance. See [here](https://github.com/connor-makowski/type_enforced#validate-class-instances-and-classes)

**Comment by connor-makowski** [comment]
@cmantas I am assuming that this addresses your issue. Feel free to reopen if this is not the case.
