### ISSUE TITLE
Future annotations does errors when using type_enforced.Enforcer

### ISSUE THREAD

**Issue by liadlevy-pando** [connor-makowski/type_enforced#35]
Hi,

I have an issue when importing 
`from __future__ import annotations`

It will lead to

`TypeError: (xxx.__init__): Type mismatch for typed variable `yyyy`. Expected one of the following `['dict']` but got `<class 'dict'>` instead.`

```
@type_enforced.Enforcer(enabled=True)
class xxx:
    def __init__(self, vvvv=None, metadata: bbb = None, ccc=None) -> None:
        pass


xxx(vvvv="1 data", bbb={"s": "s"})

```
When deleting the import all works as expected

Thanks

**Comment by connor-makowski** [comment]
Hi @liadlevy-pando! Thanks for creating an issue.

Unfortunately `__future__.annotations` is actually quite the breaking change in python deep under the hood. It has been delayed until python 4.0 as of my last check.

With that said, I should probably add some notes to the documentation to make this more clear.

I will also consider adding `__future_.annotations` support. Let me mull this over a bit and update my thoughts here soon.

Tagging https://github.com/connor-makowski/type_enforced/issues/27 as a related issue.

Connor

**Comment by Ashark** [comment]
I am having exactly #27 issue. There seems to be no workaround (besides commenting `from __future__ import annotations`)?

I tried:
```python
import sys
if sys.version_info < (3, 10):
    from __future__ import annotations
```
but then I get `SyntaxError: from __future__ imports must occur at the beginning of the file`.

I also tried
```python
from __future__ import annotations
import sys
if sys.version_info > (3, 9):
    sys.modules.pop("annotations")
```
it says `KeyError: 'annotations'`.

Also tried:
```python
from __future__ import annotations
import sys
if sys.version_info > (3, 9):
    del annotations
```

but still getting ``Type mismatch for typed variable `options`. Expected one of the following `['list']` but got `<class 'list'>` instead.``.

**Comment by Ashark** [comment]
It also seems I cannot just omit `from __future__ import annotations` for python > 3.9, because then cleaner annotations cannot be used with TYPE_CHECKING (see https://stackoverflow.com/a/39757388/7869636):

I.e. I would need to use string instead of class name:
```python
# some_file.py

# <-- See, I do not have from __future__ import annotations
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from main import Main

class MyObject(object):
    def func2(self, some_param: 'Main'):  # <-- see, I have to use 'Main' as a string
```

In other words, I cannot have cleaner annotations and type-enforcer at the same time :(.

**Comment by connor-makowski** [comment]
Hey. Unfortunately, solving this issue about future is not something I can currently work on. For now, I just updated the main documentation to note that this is not supported at the moment. This may be something that is worked on in the future.

Tagging related commit: https://github.com/connor-makowski/type_enforced/commit/08d8d24d7c360f9280412b7903f1a0a175a9bf2a

**Comment by connor-makowski** [comment]
> It also seems I cannot just omit `from __future__ import annotations` for python > 3.9, because then cleaner annotations cannot be used with TYPE_CHECKING (see https://stackoverflow.com/a/39757388/7869636):
> 
> I.e. I would need to use string instead of class name:
> 
> ```python
> # some_file.py
> 
> # <-- See, I do not have from __future__ import annotations
> from typing import TYPE_CHECKING
> if TYPE_CHECKING:
>     from main import Main
> 
> class MyObject(object):
>     def func2(self, some_param: 'Main'):  # <-- see, I have to use 'Main' as a string
> ```
> 
> In other words, I cannot have cleaner annotations and type-enforcer at the same time :(.
> 
> Also, even if I go with string approach, then type-enforcer (1.4.0) still fails to understand that:
> 
> > Type mismatch for typed variable `some_param`. Expected one of the following `["Main"]` but got `<class "Main">` instead.

See my comments here: https://github.com/connor-makowski/type_enforced/issues/32#issuecomment-2034614463

**Comment by C0rn3j** [comment]
Annotations are included with Python 3.14, does this mean this project cannot work with it there at all, or that it now works since it is no longer a future import?

https://docs.python.org/3.14/whatsnew/3.14.html#pep-649-deferred-evaluation-of-annotations

**Comment by connor-makowski** [comment]
@C0rn3j : If the future of annotations is finally arriving, then this will require some updates on the type_enforced side. I will have to start testing 3.14 and find some way for backwards compatibility.

Thanks for the update!

**Comment by connor-makowski** [comment]
See updates here: 49ad4066792c5ab28d28fbc2aacb24523b10025f

Expected release in 1.9.0

**Comment by connor-makowski** [comment]
Closing with: https://github.com/connor-makowski/type_enforced/releases/tag/1.9.0

**Comment by C0rn3j** [comment]
![Image](https://github.com/user-attachments/assets/f6ea8bc5-147a-4612-b28c-5e7abd3d3315)

```python

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/c0rn3j/Projects/Tauon/src/tauon/__main__.py", line 481, in <module>
    main()
    ~~~~^^
  File "/home/c0rn3j/Projects/Tauon/src/tauon/__main__.py", line 478, in main
    from tauon.t_modules import t_main
  File "/home/c0rn3j/Projects/Tauon/src/tauon/t_modules/t_main.py", line 40283, in <module>
    gnome = Gnome(tauon)
  File "/home/c0rn3j/Projects/Tauon/src/tauon/t_modules/t_dbus.py", line 54, in __init__
    tauon.set_tray_icons()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/type_enforced/enforcer.py", line 187, in __get_fn__
    return self.__call__(*args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/type_enforced/enforcer.py", line 221, in __call__
    self.__check_type__(assigned_vars.get(key), value, key)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/type_enforced/enforcer.py", line 242, in __check_type__
    self.__exception__(
    ~~~~~~~~~~~~~~~~~~^
        f"Type mismatch for typed variable `{key}`. Expected one of the following `{str(list(acceptable_types.keys()))}` but got `{passed_type}` instead."
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/type_enforced/enforcer.py", line 176, in __exception__
    raise TypeError(f"({self.__fn__.__qualname__}): {message}")
TypeError: (Tauon.set_tray_icons): Type mismatch for typed variable `force`. Expected one of the following `['bool']` but got `<class 'bool'>` instead.
```

Still same error as OP on 1.9.0, Python 3.13 with a future import.

Tried to enforce the Tauon class here - https://github.com/Taiko2k/Tauon/blob/34bb6a4fcc40918f8ca087c7067845966d2acd63/src/tauon/t_modules/t_main.py#L5017

And ended up crashing on t_dbus.py in here:

```python
class Gnome:

	def __init__(self, tauon: Tauon) -> None:

		self.bus_object = None
		self.tauon = tauon
		self.indicator_launched = False
		self.indicator_mode = 0
		self.update_tray_text = None
		self.tray_text = ""
		self.resume_playback = False


		tauon.set_tray_icons() # takes optional "forced" bool argument
```

**Comment by connor-makowski** [comment]
There were some odd things happening under the hood for from future imports depending on major python version. I added some tests and generalized this, however, it did require me to drop support for python 3.9 (it was about time anyway). 

In any case, just dropped `1.10.0` which fixed a number of bugs related to `from future` and also streamlining some of the code to work better across versions.

Would love to get an example if you are still having issues on 1.10.0

**Comment by C0rn3j** [comment]
That seems to work!

However, if I enable it for a class, and then enable it AGAIN for a definition of a function within that class, it crashes:

```python

@type_enforced.Enforcer()
class Tauon:
	"""Root class for everything Tauon"""
	def __init__(self):

		self.t_title = t_title
		self.t_version = t_version
...

	@type_enforced.Enforcer()
	def set_tray_icons(self, force: bool = False):

		indicator_icon_play =    str(pctl.install_directory / "assets/svg/tray-indicator-play.svg")
...
```

```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/c0rn3j/Projects/Tauon/src/tauon/__main__.py", line 481, in <module>
    main()
    ~~~~^^
  File "/home/c0rn3j/Projects/Tauon/src/tauon/__main__.py", line 478, in main
    from tauon.t_modules import t_main
  File "/home/c0rn3j/Projects/Tauon/src/tauon/t_modules/t_main.py", line 40284, in <module>
    gnome = Gnome(tauon)
  File "/home/c0rn3j/Projects/Tauon/src/tauon/t_modules/t_dbus.py", line 54, in __init__
    tauon.set_tray_icons()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/type_enforced/enforcer.py", line 187, in __get_fn__
    return self.__call__(*args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/type_enforced/enforcer.py", line 216, in __call__
    **dict(zip(self.__fn__.__code__.co_varnames[: len(args)], args)),
               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FunctionMethodEnforcer' object has no attribute '__code__'. Did you mean: '__call__'?
```

Now, I can seem to do `enabled=False` for it, and that works, but double-enabling should probably not crash like this even if it seems to be user error, it should crash with a bit more understandable error perhaps?

Is there a simple way to enable the checking for an entire .py file with about 80 classes and even more function defs?

**Comment by connor-makowski** [comment]
Thansk for the follow up. I modified a test to check for double enforcement and fixed the bug.

1.10.1

Regarding wrapping all classes / functions in a file automatically, you could probably use `ast` for that or loop over globals at the end of the file wrapping all callables with the enforcer... I am not sure of a way to genericize that off the top of my head. Might be worth creating a new ticket.

**Comment by C0rn3j** [comment]
Looks good, I think the original issue is now solved, I'll open new issues for the rest of the stuff, thanks a lot!
